#!/usr/bin/env sh

power_off=' Power off'
reboot=' Reboot'
lock=' Lock'

chosen=$(printf '%s;%s;' "$reboot" "$power_off" | rofi -dmenu -sep ';' -selected-row 0)
 
case "$chosen" in
  "$power_off")
    poweroff
    ;;

  "$reboot")
     reboot
    ;;

  *) exit 1 ;;
esac
